eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
  instance:
    prefer-ip-address: true
info:
  module.name: consumer
  organization.name: neu
  author.name: ccw